
import React, { useState, useEffect } from 'react';
import { getContent } from '../../services/contentService';
import { getTotalPlatformUsage } from '../../services/userService';
import { type TutorialContent, type User, type Language } from '../../types';
import { ChevronDownIcon, ImageIcon, VideoIcon, PlayIcon } from '../Icons';

interface ECourseViewProps {
    currentUser: User;
    language: Language;
}

const ECourseView: React.FC<ECourseViewProps> = ({ currentUser }) => {
  const [content, setContent] = useState<TutorialContent | null>(null);
  const [isTutorialsVisible, setIsTutorialsVisible] = useState(false);
  const [platformStats, setPlatformStats] = useState<{ totalImages: number; totalVideos: number } | null>(null);

  useEffect(() => {
    const fetchPageData = async () => {
        const contentData = await getContent();
        setContent(contentData);
        
        // Fetch platform stats
        const stats = await getTotalPlatformUsage();
        setPlatformStats(stats);
    };
    fetchPageData();
  }, []);

  if (!content) {
    return (
        <div className="flex items-center justify-center h-full">
            <div className="animate-pulse flex flex-col items-center">
                <div className="h-12 w-12 bg-neutral-200 rounded-full mb-4"></div>
                <div className="h-4 w-32 bg-neutral-200 rounded"></div>
            </div>
        </div>
    );
  }

  return (
    <div className="max-w-[1600px] mx-auto space-y-6 sm:space-y-8">
      
      {/* Grid for Getting Started and Platform Stats */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 sm:gap-8">
        
        {/* Panel 1: Getting Started */}
        <div className="bg-white dark:bg-neutral-900 p-6 sm:p-8 rounded-3xl shadow-soft border border-neutral-100 dark:border-neutral-800 h-full flex flex-col transition-all hover:shadow-hover">
            <h2 className="text-xl sm:text-3xl font-bold mb-4 sm:mb-6 text-neutral-900 dark:text-white">Getting Started</h2>
            <div className="relative aspect-video mb-4 sm:mb-6 flex-shrink-0 rounded-2xl overflow-hidden shadow-lg group">
              <iframe 
                className="w-full h-full rounded-2xl"
                src={content.mainVideoUrl}
                title="YouTube video player" 
                frameBorder="0" 
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                allowFullScreen>
              </iframe>
            </div>
            <div className="space-y-2 sm:space-y-3 flex-1">
              <h3 className="text-lg sm:text-2xl font-bold text-neutral-900 dark:text-white">{content.mainTitle}</h3>
              <p className="text-sm sm:text-base text-neutral-500 dark:text-neutral-400 leading-relaxed">{content.mainDescription}</p>
            </div>
        </div>

        {/* Panel 2: Total Generated Content */}
        <div className="bg-white dark:bg-neutral-900 p-6 sm:p-8 rounded-3xl shadow-soft border border-neutral-100 dark:border-neutral-800 h-full flex flex-col">
            <h2 className="text-xl sm:text-3xl font-bold mb-6 sm:mb-8 text-neutral-900 dark:text-white">Platform Activity</h2>
            
            <div className="flex-1 flex flex-col justify-center gap-6 sm:gap-8">
                <div className="text-center mb-2">
                    <p className="text-neutral-500 dark:text-neutral-400 text-xs sm:text-sm font-medium uppercase tracking-wide">Total content generated by all MONOklix users</p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
                    {/* Images Stat */}
                    <div className="bg-neutral-50 dark:bg-neutral-800/50 p-6 sm:p-8 rounded-2xl border border-neutral-100 dark:border-neutral-800 flex flex-col items-center justify-center text-center hover:scale-[1.02] transition-transform duration-300 shadow-sm hover:shadow-md group">
                        <div className="w-12 h-12 sm:w-16 sm:h-16 rounded-2xl bg-gradient-to-br from-blue-500/10 to-indigo-500/10 flex items-center justify-center mb-4 group-hover:from-blue-500/20 group-hover:to-indigo-500/20 transition-colors">
                            <ImageIcon className="w-6 h-6 sm:w-8 sm:h-8 text-blue-600 dark:text-blue-400" />
                        </div>
                        <h3 className="text-2xl sm:text-4xl font-extrabold text-neutral-900 dark:text-white mb-1">
                            {platformStats ? platformStats.totalImages.toLocaleString() : '...'}
                        </h3>
                        <p className="text-xs sm:text-sm font-semibold text-neutral-500 dark:text-neutral-400 uppercase tracking-wider">Total Images</p>
                    </div>

                    {/* Videos Stat */}
                    <div className="bg-neutral-50 dark:bg-neutral-800/50 p-6 sm:p-8 rounded-2xl border border-neutral-100 dark:border-neutral-800 flex flex-col items-center justify-center text-center hover:scale-[1.02] transition-transform duration-300 shadow-sm hover:shadow-md group">
                        <div className="w-12 h-12 sm:w-16 sm:h-16 rounded-2xl bg-gradient-to-br from-purple-500/10 to-pink-500/10 flex items-center justify-center mb-4 group-hover:from-purple-500/20 group-hover:to-pink-500/20 transition-colors">
                            <VideoIcon className="w-6 h-6 sm:w-8 sm:h-8 text-purple-600 dark:text-purple-400" />
                        </div>
                        <h3 className="text-2xl sm:text-4xl font-extrabold text-neutral-900 dark:text-white mb-1">
                            {platformStats ? platformStats.totalVideos.toLocaleString() : '...'}
                        </h3>
                        <p className="text-xs sm:text-sm font-semibold text-neutral-500 dark:text-neutral-400 uppercase tracking-wider">Total Videos</p>
                    </div>
                </div>
                
                <div className="mt-4 p-4 bg-neutral-50 dark:bg-neutral-800/30 rounded-xl text-center border border-neutral-100 dark:border-neutral-800/50">
                    <p className="text-[10px] sm:text-xs text-neutral-400 dark:text-neutral-500 font-medium">
                        Data is updated in real-time as users create content.
                    </p>
                </div>
            </div>
        </div>

      </div>

      {content.tutorials.length > 0 && (
        <div className="pt-6 sm:pt-8 border-t border-neutral-200 dark:border-neutral-800">
          <div 
            onClick={() => setIsTutorialsVisible(!isTutorialsVisible)}
            className="flex justify-between items-center cursor-pointer group select-none"
            aria-expanded={isTutorialsVisible}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') setIsTutorialsVisible(!isTutorialsVisible) }}
          >
            <h2 className="text-lg sm:text-2xl font-bold text-neutral-900 dark:text-white group-hover:text-brand-start transition-colors flex items-center gap-3">
                <span className="w-1.5 h-6 sm:w-2 sm:h-8 bg-brand-start rounded-full"></span>
                Video Tutorials
            </h2>
            <div className={`p-2 rounded-full bg-neutral-100 dark:bg-neutral-800 transition-transform duration-300 ${isTutorialsVisible ? 'rotate-180 bg-brand-start/10 text-brand-start' : 'text-neutral-500'}`}>
                <ChevronDownIcon className="w-5 h-5 sm:w-6 sm:h-6" />
            </div>
          </div>
          
          <div className={`grid overflow-hidden transition-all duration-500 ease-custom-ease ${isTutorialsVisible ? 'grid-rows-[1fr] opacity-100 mt-6 sm:mt-8' : 'grid-rows-[0fr] opacity-0 mt-0'}`}>
              <div className="overflow-hidden">
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">
                    {content.tutorials.map((tutorial, index) => (
                      <div key={index} className="bg-white dark:bg-neutral-900 rounded-2xl p-5 sm:p-6 flex flex-col shadow-soft border border-neutral-100 dark:border-neutral-800 hover:shadow-hover transition-all duration-300 hover:-translate-y-1">
                        <div className="flex-1">
                          <div className="aspect-video bg-neutral-100 dark:bg-neutral-800 rounded-xl mb-4 sm:mb-5 flex items-center justify-center font-semibold text-neutral-400 overflow-hidden relative group">
                            {tutorial.thumbnailUrl ? (
                              <>
                                <img src={tutorial.thumbnailUrl} alt={tutorial.title} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" />
                                <div className="absolute inset-0 bg-black/20 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                                    <div className="w-12 h-12 bg-white/90 rounded-full flex items-center justify-center shadow-lg backdrop-blur-sm">
                                        <PlayIcon className="w-5 h-5 text-brand-start ml-1" />
                                    </div>
                                </div>
                              </>
                            ) : (
                              <span>Tutorial {index + 1}</span>
                            )}
                          </div>
                          <h3 className="font-bold text-base sm:text-lg mb-2 text-neutral-900 dark:text-white line-clamp-1">{tutorial.title}</h3>
                          <p className="text-xs sm:text-sm text-neutral-500 dark:text-neutral-400 line-clamp-2 leading-relaxed">{tutorial.description}</p>
                        </div>
                        <a href="#" className="text-brand-start font-semibold mt-4 sm:mt-5 text-sm hover:text-brand-end transition-colors flex items-center gap-1 group/link">
                            Watch now 
                            <span className="group-hover/link:translate-x-1 transition-transform">→</span>
                        </a>
                      </div>
                    ))}
                  </div>
              </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ECourseView;
